
namespace Server
{
    partial class Form1
    {
       
        private System.ComponentModel.IContainer components = null;

        
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Code generated by forms designer

       
        private void InitializeComponent()
        {
            this.button_Accpet = new System.Windows.Forms.Button();
            this.richTextBox_Receive = new System.Windows.Forms.RichTextBox();
            this.label1 = new System.Windows.Forms.Label();
            this.textBox_Port = new System.Windows.Forms.TextBox();
            this.label2 = new System.Windows.Forms.Label();
            this.textBox_Addr = new System.Windows.Forms.TextBox();
            this.richTextBox_Send = new System.Windows.Forms.RichTextBox();
            this.button_Close = new System.Windows.Forms.Button();
            this.helpProvider1 = new System.Windows.Forms.HelpProvider();
            this.button_Clear = new System.Windows.Forms.Button();
            this.button_cache_file = new System.Windows.Forms.Button();
            this.SuspendLayout();
            // 
            // button_Accpet
            // 
            this.button_Accpet.Font = new System.Drawing.Font("Agency FB", 16F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.button_Accpet.Location = new System.Drawing.Point(56, 222);
            this.button_Accpet.Margin = new System.Windows.Forms.Padding(4);
            this.button_Accpet.Name = "button_Accpet";
            this.button_Accpet.Size = new System.Drawing.Size(154, 62);
            this.button_Accpet.TabIndex = 0;
            this.button_Accpet.Text = "Recieve";
            this.button_Accpet.UseVisualStyleBackColor = true;
            this.button_Accpet.Click += new System.EventHandler(this.button_Accpet_Click);
            // 
            // richTextBox_Receive
            // 
            this.richTextBox_Receive.Font = new System.Drawing.Font("Microsoft Sans Serif", 15F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.richTextBox_Receive.Location = new System.Drawing.Point(519, 38);
            this.richTextBox_Receive.Margin = new System.Windows.Forms.Padding(4);
            this.richTextBox_Receive.Name = "richTextBox_Receive";
            this.richTextBox_Receive.Size = new System.Drawing.Size(788, 529);
            this.richTextBox_Receive.TabIndex = 1;
            this.richTextBox_Receive.Text = "";
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("宋体", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
            this.label1.Location = new System.Drawing.Point(30, 120);
            this.label1.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(77, 29);
            this.label1.TabIndex = 2;
            this.label1.Text = "PORT";
            // 
            // textBox_Port
            // 
            this.textBox_Port.Font = new System.Drawing.Font("Microsoft Sans Serif", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.textBox_Port.Location = new System.Drawing.Point(165, 111);
            this.textBox_Port.Margin = new System.Windows.Forms.Padding(4);
            this.textBox_Port.Name = "textBox_Port";
            this.textBox_Port.Size = new System.Drawing.Size(320, 40);
            this.textBox_Port.TabIndex = 3;
            this.textBox_Port.Text = "8045";
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Font = new System.Drawing.Font("宋体", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
            this.label2.Location = new System.Drawing.Point(3, 46);
            this.label2.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(125, 29);
            this.label2.TabIndex = 4;
            this.label2.Text = "ADDRESS";
            // 
            // textBox_Addr
            // 
            this.textBox_Addr.Font = new System.Drawing.Font("Microsoft Sans Serif", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.textBox_Addr.Location = new System.Drawing.Point(165, 38);
            this.textBox_Addr.Margin = new System.Windows.Forms.Padding(4);
            this.textBox_Addr.Name = "textBox_Addr";
            this.textBox_Addr.Size = new System.Drawing.Size(320, 40);
            this.textBox_Addr.TabIndex = 5;
            this.textBox_Addr.Text = "127.0.0.1";
            // 
            // richTextBox_Send
            // 
            this.richTextBox_Send.Font = new System.Drawing.Font("Microsoft Sans Serif", 14.25F, System.Drawing.FontStyle.Bold);
            this.richTextBox_Send.Location = new System.Drawing.Point(519, 602);
            this.richTextBox_Send.Margin = new System.Windows.Forms.Padding(4);
            this.richTextBox_Send.Name = "richTextBox_Send";
            this.richTextBox_Send.Size = new System.Drawing.Size(788, 242);
            this.richTextBox_Send.TabIndex = 8;
            this.richTextBox_Send.Text = "";
            // 
            // button_Close
            // 
            this.button_Close.Font = new System.Drawing.Font("Agency FB", 16F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.button_Close.Location = new System.Drawing.Point(267, 222);
            this.button_Close.Margin = new System.Windows.Forms.Padding(4);
            this.button_Close.Name = "button_Close";
            this.button_Close.Size = new System.Drawing.Size(154, 62);
            this.button_Close.TabIndex = 10;
            this.button_Close.Text = "Close";
            this.button_Close.UseVisualStyleBackColor = true;
            this.button_Close.Click += new System.EventHandler(this.button_Close_Click);
            // 
            // helpProvider1
            // 
            this.helpProvider1.Tag = "When the client is closed, click to continue listening to the client. After click" +
    "ing, the program will be interrupted";
            // 
            // button_Clear
            // 
            this.button_Clear.Font = new System.Drawing.Font("Agency FB", 16F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.button_Clear.Location = new System.Drawing.Point(165, 730);
            this.button_Clear.Name = "button_Clear";
            this.button_Clear.Size = new System.Drawing.Size(100, 44);
            this.button_Clear.TabIndex = 11;
            this.button_Clear.Text = "Clear";
            this.button_Clear.UseVisualStyleBackColor = true;
            this.button_Clear.Click += new System.EventHandler(this.button_Clear_Click);
            // 
            // button_cache_file
            // 
            this.button_cache_file.Location = new System.Drawing.Point(140, 355);
            this.button_cache_file.Name = "button_cache_file";
            this.button_cache_file.Size = new System.Drawing.Size(199, 54);
            this.button_cache_file.TabIndex = 12;
            this.button_cache_file.Text = "Cached file";
            this.button_cache_file.UseVisualStyleBackColor = true;
            this.button_cache_file.Click += new System.EventHandler(this.button_cache_file_Click);
            // 
            // Form1
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(9F, 18F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1341, 868);
            this.Controls.Add(this.button_cache_file);
            this.Controls.Add(this.button_Clear);
            this.Controls.Add(this.button_Close);
            this.Controls.Add(this.richTextBox_Send);
            this.Controls.Add(this.textBox_Addr);
            this.Controls.Add(this.label2);
            this.Controls.Add(this.textBox_Port);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.richTextBox_Receive);
            this.Controls.Add(this.button_Accpet);
            this.Margin = new System.Windows.Forms.Padding(4);
            this.Name = "Form1";
            this.Text = "CACHE";
            this.Load += new System.EventHandler(this.Form1_Load);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.Button button_Accpet;
        private System.Windows.Forms.RichTextBox richTextBox_Receive;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.TextBox textBox_Port;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.TextBox textBox_Addr;
        private System.Windows.Forms.RichTextBox richTextBox_Send;
        private System.Windows.Forms.Button button_Close;
        private System.Windows.Forms.HelpProvider helpProvider1;
        private System.Windows.Forms.Button button_Clear;
        private System.Windows.Forms.Button button_cache_file;
    }
}

